alerts:
  enabled: true
  market_switch_alerts: true
  performance_comparison_alerts: true
api:
  key: ${BINANCE_API_KEY}
  secret: ${BINANCE_API_SECRET}
default_market_type: spot
exchange:
  name: binance
  supported_markets:
  - futures
  - spot
grid:
  futures:
    leverage: 1
    position_side: BOTH
    use_isolated_margin: false
  initial_levels: 10
  initial_spacing_perc: '0.005'
  leverage: 1
  spot:
    max_base_asset_allocation: 0.5
    min_order_size_usd: 10
logging:
  level: INFO
  log_file: logs/bot.log
  log_to_console: true
  market_performance_log: logs/market_performance.csv
  trade_log_file: logs/trades.csv
operation_mode: Production
pair_selection:
  blacklist:
  - EXAMPLE/USDT
  futures_pairs:
    min_open_interest_usd: 50000000
    preferred_symbols:
    - BTCUSDT
    - ETHUSDT
    - ADAUSDT
  max_adx: 25
  max_spread_perc: 0.1
  min_atr_perc_24h: 2.0
  min_volume_usd_24h: 100000000
  spot_pairs:
    min_liquidity_depth: 1000000
    preferred_symbols:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  update_interval_hours: 6
risk_management:
  api_failure_timeout_minutes: 5
  dynamic_sl_profit_lock_perc: 80.0
  futures_risk:
    liquidation_buffer_perc: 15.0
    max_leverage: 20
    max_position_size_perc: 50.0
  loss_protection_trigger_perc: 15.0
  max_drawdown_perc: 10.0
  spot_risk:
    max_asset_allocation_perc: 70.0
    min_stable_balance_perc: 30.0
  tp_sl_ratio: 3.0
rl_agent:
  algorithm: PPO
  experience_replay_buffer_size: 10000
  market_decision:
    enabled: true
    market_consistency_bonus: 0.05
    market_switch_reward_bonus: 0.1
  retraining_trade_threshold: 100
  reward_function:
    drawdown_penalty: 0.5
    inefficiency_penalty: 0.2
    market_switch_penalty: 0.1
    profit_weight: 1.0
  state_features:
  - rsi
  - atr
  - adx
  - volume
  - grid_context
  - market_performance
  training_frequency_steps: 1000
sentiment_analysis:
  alerts:
    alert_cooldown_minutes: 120
    enabled: true
    negative_threshold: -0.5
    positive_threshold: 0.7
  enabled: true
  fetch_interval_minutes: 60
  pair_filtering:
    enabled: true
    min_sentiment_for_new_pair: -0.3
  reddit:
    comments_limit_per_post: 5
    enabled: true
    posts_limit_per_subreddit: 10
    subreddits:
    - wallstreetbets
    - investing
    - CryptoCurrency
    time_filter: day
  binance_news:
    enabled: true
    fetch_interval_minutes: 30
    hours_back: 24
    min_relevance_score: 0.2
    max_news_per_fetch: 20
    include_announcements: true
    include_general_news: true
    include_trending: true
  risk_adjustment:
    enabled: true
    leverage_reduction_factor: 0.5
    leverage_reduction_threshold: -0.5
  rl_feature:
    enabled: true
  smoothing_window: 10
trading:
  allow_market_switching: true
  capital_per_pair_usd: '8'  # Reduzido de 10 para 8 USD
  cycle_interval_seconds: 60
  market_allocation:
    futures_percentage: 60
    spot_percentage: 40
  market_switch_cooldown_minutes: 30
  max_concurrent_pairs: 2  # Reduzido de 3 para 2 pares simultâneos
ai_agent:
  enabled: true
  base_url: "http://127.0.0.1:11434"
  # model_name: auto-detect from currently running model
  features:
    market_analysis: true
    grid_optimization: true
    sentiment_analysis: true
    decision_explanation: true
    report_generation: true
  analysis_interval_minutes: 15
  optimization_interval_hours: 4
  report_generation:
    daily_report: true
    pair_analysis: true
    performance_summary: true
  model_settings:
    temperature: 0.3
    max_tokens: 1000
    timeout_seconds: 30
  # Model Testing Configuration
  model_presets:
    qwen3_fast: 
      model_name: "qwen3:0.6b"
      temperature: 0.2
      max_tokens: 500
    qwen3_balanced:
      model_name: "qwen3:1.7b"
      temperature: 0.3
      max_tokens: 800
    qwen3_detailed:
      model_name: "qwen3:4b"
      temperature: 0.4
      max_tokens: 1200
    deepseek_reasoning:
      model_name: "deepseek-r1:1.5b"
      temperature: 0.2
      max_tokens: 1000
    gemma3_fast:
      model_name: "gemma3:1b"
      temperature: 0.3
      max_tokens: 600
    gemma3_balanced:
      model_name: "gemma3:4b"
      temperature: 0.3
      max_tokens: 1000
