alerts:
  enabled: true
  market_switch_alerts: true
  performance_comparison_alerts: true
api:
  key: ${BINANCE_API_KEY}
  secret: ${BINANCE_API_SECRET}
default_market_type: futures
exchange:
  name: binance
  supported_markets:
  - futures
  - spot
grid:
  futures:
    leverage: 10  # Alavancagem inicial 10x para maximizar capital
    max_leverage: 15  # Máximo 15x permitido
    position_side: BOTH
    use_isolated_margin: false
  initial_levels: 5  # Reduzido para 5 níveis para maior capital por ordem
  initial_spacing_perc: '0.002'  # 0.2% spacing para melhor spread
  leverage: 1
  spot:
    max_base_asset_allocation: 0.5
    min_order_size_usd: 5  # Mínimo $5 conforme requisito da Binance
logging:
  level: INFO
  log_file: logs/bot.log
  log_to_console: true
  market_performance_log: logs/market_performance.csv
  trade_log_file: logs/trades.csv
operation_mode: Production
pair_selection:
  blacklist:
  - EXAMPLE/USDT
  - 1000000BOBUSDT
  - HOMEUSDT
  - SQDUSDT
  - RVNUSDT
  - BTCUSDT    # Removido por preço muito alto
  - ETHUSDT    # Removido por preço muito alto
  - BNBUSDT    # Removido por preço muito alto
  - SOLUSDT    # Removido por preço muito alto
  use_social_feed_analysis: false  # Temporariamente desabilitado para estabilidade
  futures_pairs:
    min_open_interest_usd: 20000000  # Reduzido para incluir mais pares
    max_price_usdt: 1.0             # NOVO: Excluir pares com preço > 1 USDT
    preferred_symbols:
    # Pares com alta liquidez e preço < 1 USDT
    - XRPUSDT    # ~$0.5-0.7, alta liquidez
    - ADAUSDT    # ~$0.3-0.5, alta liquidez  
    - DOGEUSDT   # ~$0.05-0.1, muito alta liquidez
    - TRXUSDT    # ~$0.05-0.1, boa liquidez
    - XLMUSDT    # ~$0.05-0.1, boa liquidez
    - MATICUSDT  # ~$0.3-0.8, alta liquidez
    - FTMUSDT    # ~$0.2-0.8, boa liquidez
    - ALGOUSDT   # ~$0.1-0.3, boa liquidez
    - VETUSDT    # ~$0.02-0.05, alta liquidez
    - ZILUSDT    # ~$0.01-0.03, boa liquidez
    - ONTUSDT    # ~$0.1-0.3, média liquidez
    - ICXUSDT    # ~$0.1-0.3, média liquidez
    - IOTAUSDT   # ~$0.1-0.3, média liquidez
    - EOSUSDT    # ~$0.4-1.2, limite do preço
    - CELRUSDT   # ~$0.01-0.03, boa liquidez
    - DENTUSDT   # ~$0.001-0.002, muito baixo preço
    - HOTUSDT    # ~$0.001-0.003, muito baixo preço
    - WINUSDT    # ~$0.00008-0.0002, extremamente baixo
    - BTTCUSDT   # ~$0.0000008-0.000002, extremamente baixo
    - SHIBUSDT   # ~$0.000007-0.00002, extremamente baixo
    - PEPEUSDT   # ~$0.000001-0.000008, extremamente baixo
    - FLOKIUSDT  # ~$0.00008-0.0003, muito baixo preço
    - 1000BONKUSDT # ~$0.01-0.03, baixo preço (1000x)
    - 1000PEPEUSDT # ~$0.008-0.02, baixo preço (1000x)
  max_adx: 30                       # Aumentado para incluir mais pares
  max_spread_perc: 0.15            # Aumentado para incluir mais pares
  min_atr_perc_24h: 0.8            # Reduzido para incluir mais pares
  min_volume_usd_24h: 5000000      # Reduzido para incluir mais pares
  spot_pairs:
    min_liquidity_depth: 1000000
    preferred_symbols:
    - BTCUSDT
    - ETHUSDT
    - BNBUSDT
  update_interval_hours: 6
  # Configuração para análise de feeds sociais e notícias
  social_feed_analysis:
    max_news_hours: 24                    # Analisar notícias das últimas 24h
    max_feed_items: 50                    # Máximo 50 posts do feed social
    min_mentions_threshold: 2             # Mínimo 2 menções para considerar trending
    symbol_confidence_threshold: 0.4      # Confiança mínima 40%
    influencer_weight_multiplier: 2.0     # Dar 2x mais peso para posts de influenciadores
    news_weight_multiplier: 1.5           # Dar 1.5x mais peso para notícias oficiais
    use_ai_analysis: true                 # Usar IA local para análise avançada de feeds
risk_management:
  api_failure_timeout_minutes: 5
  dynamic_sl_profit_lock_perc: 80.0
  futures_risk:
    liquidation_buffer_perc: 15.0
    max_leverage: 20
    max_position_size_perc: 50.0
  loss_protection_trigger_perc: 15.0
  max_drawdown_perc: 10.0
  spot_risk:
    max_asset_allocation_perc: 70.0
    min_stable_balance_perc: 30.0
  tp_sl_ratio: 3.0
  # Configuração do Trailing Stop
  trailing_stop:
    enabled: true                    # Ativar trailing stop
    trail_amount: 1.0               # 1% de trailing distance
    trail_type: "percentage"        # "percentage" ou "fixed"
    activation_threshold: 0.5       # 0.5% de lucro para ativar trailing
    min_trail_distance: 0.001       # Distância mínima (0.1%)
    max_trail_distance: 0.05        # Distância máxima (5%)
    update_frequency: 5             # Atualizar a cada 5 segundos
  # Configuração de Ordens Condicionais
  conditional_orders:
    enabled: true                   # Ativar ordens condicionais
    check_interval_seconds: 10      # Intervalo de verificação
    max_orders_per_symbol: 5        # Máximo de ordens por símbolo
    default_expiry_minutes: 60      # Expiração padrão (60 min)
    rsi_oversold_threshold: 30      # RSI oversold padrão
    rsi_overbought_threshold: 70    # RSI overbought padrão
    volume_spike_multiplier: 2.0    # Multiplicador para spike de volume
    use_stop_limit_orders: true     # Preferir STOP_LIMIT ao invés de STOP_MARKET
rl_agent:
  enabled: false  # RL desabilitado para reduzir dependências
  algorithm: PPO
  experience_replay_buffer_size: 10000
  market_decision:
    enabled: false
    market_consistency_bonus: 0.05
    market_switch_reward_bonus: 0.1
  retraining_trade_threshold: 100
  reward_function:
    drawdown_penalty: 0.5
    inefficiency_penalty: 0.2
    market_switch_penalty: 0.1
    profit_weight: 1.0
  state_features:
  - rsi
  - atr
  - adx
  - volume
  - grid_context
  - market_performance
  training_frequency_steps: 1000
sentiment_analysis:
  alerts:
    alert_cooldown_minutes: 120
    enabled: true
    negative_threshold: -0.5
    positive_threshold: 0.7
  enabled: true
  fetch_interval_minutes: 60
  pair_filtering:
    enabled: false
    min_sentiment_for_new_pair: -0.3
  reddit:
    comments_limit_per_post: 5
    enabled: true
    posts_limit_per_subreddit: 10
    subreddits:
    - wallstreetbets
    - investing
    - CryptoCurrency
    time_filter: day
  binance_news:
    enabled: true
    fetch_interval_minutes: 30
    hours_back: 24
    min_relevance_score: 0.2
    max_news_per_fetch: 20
    include_announcements: true
    include_general_news: true
    include_trending: true
  risk_adjustment:
    enabled: true
    leverage_reduction_factor: 0.5
    leverage_reduction_threshold: -0.5
  rl_feature:
    enabled: true
  smoothing_window: 10
trading:
  allow_market_switching: true
  capital_per_pair_usd: '5'  # Mínimo $5 conforme requisito da Binance
  cycle_interval_seconds: 60
  market_allocation:
    futures_percentage: 60
    spot_percentage: 40
  market_switch_cooldown_minutes: 30
  max_concurrent_pairs: 25  # 25 pares simultâneos - máxima diversificação
ai_agent:
  enabled: true
  base_url: "http://127.0.0.1:11434"
  # model_name: auto-detect from currently running model
  features:
    market_analysis: true
    grid_optimization: true
    sentiment_analysis: true
    decision_explanation: true
    report_generation: true
  analysis_interval_minutes: 15
  optimization_interval_hours: 4
  report_generation:
    daily_report: true
    pair_analysis: true
    performance_summary: true
  model_settings:
    temperature: 0.3
    max_tokens: 1000
    timeout_seconds: 30
  # Model Testing Configuration
  model_presets:
    qwen3_fast: 
      model_name: "qwen3:0.6b"
      temperature: 0.2
      max_tokens: 500
    qwen3_balanced:
      model_name: "qwen3:1.7b"
      temperature: 0.3
      max_tokens: 800
    qwen3_detailed:
      model_name: "qwen3:4b"
      temperature: 0.4
      max_tokens: 1200
    deepseek_reasoning:
      model_name: "deepseek-r1:1.5b"
      temperature: 0.2
      max_tokens: 1000
    gemma3_fast:
      model_name: "gemma3:1b"
      temperature: 0.3
      max_tokens: 600
    gemma3_balanced:
      model_name: "gemma3:4b"
      temperature: 0.3
      max_tokens: 1000
